/**
 * Quotation Statuses Enum
 * Centralized constant references to eliminate Magic Strings across the application.
 */
const QUOTATION_STATUSES = {
    DRAFT: 'DRAFT',
    PENDING_ADMIN_REVIEW: 'PENDING_ADMIN_REVIEW',
    PENDING_CUSTOMER_APPROVAL: 'PENDING_CUSTOMER_APPROVAL',
    AWAITING_FINAL_CHARGE_SHEET: 'AWAITING_FINAL_CHARGE_SHEET',
    PAYMENT_PENDING: 'PAYMENT_PENDING',
    CONVERTED_TO_SHIPMENT: 'CONVERTED_TO_SHIPMENT',
    REJECTED: 'REJECTED',
    EXPIRED: 'EXPIRED',
    VERIFIED: 'VERIFIED',
    ADDRESS_PROVIDED: 'ADDRESS_PROVIDED',
    QUOTATION_GENERATED: 'QUOTATION_GENERATED',
    QUOTATION_SENT: 'QUOTATION_SENT',
    NEGOTIATION_REQUESTED: 'NEGOTIATION_REQUESTED',
    ACCEPTED: 'ACCEPTED',
    BOOKED: 'BOOKED',
    
    // Legacy mapping statuses
    REQUEST_SENT: 'request_sent',
    COST_CALCULATED: 'cost_calculated',
    READY_FOR_PICKUP: 'ready_for_pickup'
};

module.exports = QUOTATION_STATUSES;
